#!/bin/sh
set -e

# Ensure /code/web directory exists, preventing Apache from crashing.
mkdir -p /code/web

# Ensure $WEB_PATH starts with a slash.
WEB_PATH=$(echo ${WEB_PATH} | sed 's#^\([^/]\)#/\1#')

# If $PUBLIC_DIR is set, symlink it to /shared/public and correct permissions.
if [ "${PUBLIC_DIR}" ]; then
  mkdir -p /shared/public
  # Only create symlink if it does not already exist.
  if [ ! -h /code/${PUBLIC_DIR} ]; then
    ln -sf /shared/public /code/${PUBLIC_DIR}
  fi
  chown -R www-data:www-data /shared/public
fi

# If $PRIVATE_DIR is set, ensure it exists and has correct permissions.
if [ "${PRIVATE_DIR}" ]; then
  mkdir -p ${PRIVATE_DIR}
  chown -R www-data:www-data ${PRIVATE_DIR}
fi

exec apache2 -D FOREGROUND
